In [4]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import pylab
pylab.rcParams['figure.figsize']= (10.0,8.0)
def construct_A(X):
    A=[]
    for i in range(X.shape[1]):
        row = []
        for j in range(X.shape[1]):
            s = 0
            for d in X:
                s +=d[i]*d[j]
            row.append(s)
        A.append(row)
    return np.matrix(A)
def construct_b(X,r):
    b=[np.dot(X[:,i],r) for i in range(X.shape[1])]
    return np.matrix(b)
rg = np.random.RandomState(0)
rg.permutation(range(10))

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

In [5]:
def f(x):
    return 1 + 2*x

In [6]:
x_all = np.linspace(-2,2,100)
#x_all = np.linspace(0,8,100)
x_tr = x_all[25:75]
#print(x_tr)
x_tr = x_tr[rg.permutation(range(len(x_tr)))[:10]]
print(x_tr)
r_tr = f(x_tr)
r_all = f(x_all)

D_tr = x_tr[:,np.newaxis]
#print(D_tr)
X_tr = np.hstack((np.ones((D_tr.shape[0],1)),D_tr))

D_all = x_all[:,np.newaxis]

X_all = np.hstack((np.ones((D_all.shape[0],1)),D_all))
#print(x_all)
#print(X_all)

[ 0.06060606  0.42424242  0.78787879  0.14141414 -0.54545455 -0.90909091
  0.38383838  0.90909091  0.62626263 -0.1010101 ]


In [13]:

A= construct_A(X_tr)
print(X_tr,A)
b= construct_b(X_tr,r_tr)
print(b)


AttributeError: 'list' object has no attribute 'shape'

In [8]:
A.I*b.T

matrix([[ 1.],
        [ 2.]])

In [14]:
X=[2,3,6,4]
R=[5,7,10,12]
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=1)
X_tr=pf.fit_transform(D_tr)
A=construct_A(X_tr)
b=construct_b(X_tr,r_tr)
w=np.squeeze(np.asarray(A.I*b.T))
X_all=pf.transform(D_all)
p = np.dot(X_all,w)

AttributeError: 'list' object has no attribute 'shape'

In [12]:
w

array([ 1.,  2.])